// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Webshop.Services.ProductAPI.Data;

#nullable disable

namespace Webshop.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240709110346_ResetTables")]
    partial class ResetTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Webshop.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Salad",
                            Description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br/> Cras vehicula lacinia ligula vel dictum.",
                            ImageUrl = "https://placehold.co/604x404",
                            Name = "Caesar Salad",
                            Price = 8.9900000000000002
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Soup",
                            Description = "Suspendisse potenti. Proin mollis, urna vitae auctor fermentum.<br/> Integer quis risus ut nibh ullamcorper vestibulum.",
                            ImageUrl = "https://placehold.co/605x405",
                            Name = "Chicken Soup",
                            Price = 7.5
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Main Course",
                            Description = "Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae.<br/> Nulla facilisi.",
                            ImageUrl = "https://placehold.co/606x406",
                            Name = "Grilled Salmon",
                            Price = 20.989999999999998
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Dessert",
                            Description = "Fusce aliquam libero vel leo tristique, ac bibendum orci placerat.<br/> Maecenas consectetur justo ac nunc volutpat, nec ultricies sapien aliquet.",
                            ImageUrl = "https://placehold.co/607x407",
                            Name = "Tiramisu",
                            Price = 6.9900000000000002
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "Beverage",
                            Description = "Mauris sit amet magna ac lorem posuere gravida.<br/> Duis suscipit velit in turpis vestibulum, in tincidunt massa venenatis.",
                            ImageUrl = "https://placehold.co/608x408",
                            Name = "Mango Smoothie",
                            Price = 5.5
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryName = "Side",
                            Description = "Donec nec justo eu nunc bibendum pellentesque.<br/> Aenean fringilla justo et velit pharetra, nec vestibulum eros tempor.",
                            ImageUrl = "https://placehold.co/609x409",
                            Name = "Garlic Bread",
                            Price = 4.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
